# Use Docker environment
sudo: false

# Setup build matrix
language: php
dist: trusty
php:
  - 7.3
  - 7.4

# Dependencies
before_install:
  - composer self-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --no-interaction --prefer-source

script: phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
