# Use Docker environment
sudo: false

# Setup build matrix
language: php
#dist: trusty
#php:
#  - 5.4
#  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
#  - 7.2
#  - 7.3
#  - 7.4
jobs:
  include:
    - php: 5.3
      dist: precise

# Dependencies
#before_install:
#  - composer self-update

install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer update --no-interaction

script:
  - phpenv config-add xdebug.ini
  - phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# Cache dependencies
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
